name: Checks
on: [push]

jobs:
  install-deps:
    name: Install dependencies (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14", "16"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Cache Yarn dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('/yarn.lock') }}-${{ hashFiles('/package.json') }}
      - name: Setup Node
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ matrix.node }}
      - name: Yarn install
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install

  docs:
    name: "Docs: build and deploy"
    runs-on: ubuntu-latest
    needs: install-deps
    strategy:
      matrix:
        node: ["16"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ matrix.node }}
      - name: Fetch dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('/yarn.lock') }}-${{ hashFiles('/package.json') }}
      - name: Check if cache was hit
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          echo "Should have hit cache"
          false
      - name: Build site
        run: |
          cd docs/
          yarn build
      - name: Deploy site
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          if [ -n "$KNOWN_HOSTS" ]; then
            cd docs/
            mkdir -p ~/.ssh
            echo "$SSH_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
            chmod 600 ~/.ssh/known_hosts
            rsync -glpPrtvz \
                  --delete  \
                  -e 'ssh -p 4840' \
                  .vuepress/dist/ \
                  dodona@dolos.ugent.be:docs
          else
            echo "Skipping deploy because secrets are not available"
          fi
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}


  lib-lint:
    name: "LIB: lint"
    runs-on: ubuntu-latest
    needs: install-deps
    strategy:
      matrix:
        node: ["16"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ matrix.node }}
      - name: Fetch dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('/yarn.lock') }}-${{ hashFiles('/package.json') }}
      - name: Check if cache was hit
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          echo "Should have hit cache"
          false
      - name: Lint
        run: |
          cd lib/
          yarn lint

  library-build-test:
    name: "LIB: build and test"
    runs-on: ubuntu-latest
    needs: install-deps
    strategy:
      matrix:
        node: ["12", "14", "16"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ matrix.node }}
      - name: Fetch dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('/yarn.lock') }}-${{ hashFiles('/package.json') }}
      - name: Check if cache was hit
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          echo "Should have hit cache"
          false
      - name: Build and test
        run: |
          cd lib/
          yarn build
          yarn test -v --serial

  cli-build-test:
    name: "CLI: build"
    runs-on: ubuntu-latest
    needs: install-deps
    strategy:
      matrix:
        node: ["12", "14", "16"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ matrix.node }}
      - name: Fetch dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('/yarn.lock') }}-${{ hashFiles('/package.json') }}
      - name: Check if cache was hit
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          echo "Should have hit cache"
          false
      - name: Build and test
        run: |
          cd cli/
          yarn build --force

  cli-lint:
    name: "CLI: lint"
    runs-on: ubuntu-latest
    needs: install-deps
    strategy:
      matrix:
        node: ["16"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ matrix.node }}
      - name: Fetch dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('/yarn.lock') }}-${{ hashFiles('/package.json') }}
      - name: Check if cache was hit
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          echo "Should have hit cache"
          false
      - name: Lint
        run: |
          cd cli/
          yarn lint


  web-build-test-deploy:
    name: "Web: build, test & deploy"
    runs-on: ubuntu-latest
    needs: install-deps
    strategy:
      matrix:
        node: ["12", "14", "16"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ matrix.node }}
      - name: Fetch dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('/yarn.lock') }}-${{ hashFiles('/package.json') }}
      - name: Check if cache was hit
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          echo "Should have hit cache"
          false
      - name: Build
        run: |
          cd lib/
          yarn build
          cd ../web/
          yarn build
      - name: Deploy to staging
        if: ${{ matrix.node == '16' }}
        run: |
          if [ -n "$KNOWN_HOSTS" ]; then
            cd web/
            mkdir -p ~/.ssh
            echo "$SSH_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
            chmod 600 ~/.ssh/known_hosts
            mkdir -p "deploy/$REF"
            cp -a dist/. "deploy/$REF"
            rsync -glpPrtvz \
                  --relative \
                  --delete  \
                  -e 'ssh -p 4840' \
                  "deploy/./$REF" \
                  "dodona@dolos.ugent.be:web/"
          else
            echo "Skipping deploy because secrets are not available"
          fi
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
          REF: ${{ github.ref_name }}

  web-lint:
    name: "Web: lint"
    runs-on: ubuntu-latest
    needs: install-deps
    strategy:
      matrix:
        node: ["16"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ matrix.node }}
      - name: Fetch dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('/yarn.lock') }}-${{ hashFiles('/package.json') }}
      - name: Check if cache was hit
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          echo "Should have hit cache"
          false
      - name: Lint
        run: |
          cd web/
          yarn lint
