name: Install Dependencies
on: [workflow_call]

jobs:
  # Install Dependencies
  install:
    name: Install (Node ${{ matrix.node }}) âš¡ï¸
    runs-on: ubuntu-latest
    outputs:
      cachekey: ${{ steps.define.outputs.cachekey }}
    strategy:
      matrix:
        node: ["12", "14", "16"]
      fail-fast: false
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      
      - name: Define Cache Key
        id: define
        run: echo "::set-output name=cachekey::${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}"

      - name: Cache Yarn dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/*/node_modules
          key: ${{ steps.define.outputs.cachekey }}

      - name: Setup Node ğŸ“š
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node }}

      - name: Yarn install âš¡ï¸
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install

